linijapogona/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [

    # /welcome/
    url(r'^$', TemplateView.as_view(template_name='welcome.html'), name='welcome'),

    # /admin/
    url(r'^admin/', admin.site.urls),

    # /api/
    url(r'^api/', include('pogon1.api.urls')),

    # /pogon1/
    url(r'^pogon1/', include('pogon1.urls', namespace='pogon1')),

    # /pogon2/
    #url(r'^pogon2/', include('pogon2.urls', namespace='pogon2')),

    # /pogon3/
    #url(r'^pogon3/', include('pogon3.urls', namespace='pogon3')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pogon1/api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from pogon1.api.views import UpravljanjeViewSet, CvorViewSet

# kreiranje url pogleda za API 
router = DefaultRouter()
router.register(prefix='upravljanje', viewset=UpravljanjeViewSet)

urlpatterns = [
    url(r'^cvor/$', CvorViewSet.as_view()),
]

urlpatterns += router.urls

pogon1/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'pogon1'

from .views import (
    # admin metode
    upravljanje_list,
    upravljanje_create,
    upravljanje_detail,
    upravljanje_update,
    upravljanje_delete,

    # operater metode
    pogon,
    dokumentacija,
    upravljanje_prijava,
    upravljanje_odjava,
    )

urlpatterns = [

    # dodaj obavijesti
    url(r'^list/$', upravljanje_list, name='list'),
    url(r'^create/$', upravljanje_create, name='create'),
    url(r'^(?P<id>\d+)/$', upravljanje_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', upravljanje_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', upravljanje_delete, name='delete'),

    # linija pogona
    # /pogon/
    url(r'^$', pogon, name='pogon'),
    # /pogon/dokumentacija
    url(r'^dokumentacija/$', dokumentacija, name='dokumentacija'),
    # /pogon/prijava
    url(r'^prijava/$', upravljanje_prijava, name='prijava'),
    # /pogon/odjava
    url(r'^odjava/$', upravljanje_odjava, name='odjava'),
]

pogon1/api/models.py
# Prazan model

pogon1/models.py
# django core
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse
from kamera.kamera_stream import *

# Kamera
camera = CameraNetwork()

# Kreiraj direktorij korisnika za pohranu, media/<user>
def upload_location(instance, filename):
    return '%s/%s' %(instance.korisnik, filename)

# Modeli linije pogona
class Upravljanje(models.Model):
    # korisnik
    korisnik = models.ForeignKey(User, default=1)

    # ostali detalji modela
    title = models.CharField(max_length=120)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    image = models.FileField(upload_to=upload_location, null=True, blank=True)
    user_in = models.BooleanField(default=False)

    # API
    kod = models.CharField(max_length=64, blank=False)
    mcu = models.CharField(max_length=500)
    model = models.CharField(max_length=500)
    extra = models.CharField(max_length=500)

    def __str__(self):
        return 'Operater {}: {} - {}'.format(self.korisnik, self.title, self.kod)

    def get_absolute_url(self):
        return reverse('pogon1:detail', kwargs={'id':self.id})

    def check_exists_device(kod_id):
        # Izradi kod ukoliko ne postoji

        if not Cvor.objects.filter(kod=kod_id):
            kreirao = User.objects.filter(username="linijapogona").first()
            kod_create = Cvor.objects.create(user=kreirao, kod=kod_id)

    class Meta:
        ordering = ['-timestamp', '-updated']

pogon1/forms.py
from django import forms

from .models import Upravljanje

class UpravljanjeForm(forms.ModelForm):
    class Meta:
        model = Upravljanje
        fields = [
            'korisnik',
            'title',
            'content',
            'kod',
            'mcu',
            'model',
            'extra',
            'image',
        ]

pogon1/api/views.py
from rest_framework import viewsets, generics
from pogon1.models import Upravljanje
from pogon1.api.serializers import *
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet

from pogon1.api import serializers

# Osnovni tutorial za kreiranje API pogleda
class PogonApiView(APIView):
    """Test API View."""

    # dodaj serializers varijablu i referenciraj ju
    serializers_class = serializers.UpravljanjeSerializer

    def get(self, request, format=None):
        """Returns a list of APIView features."""

        an_apiview = [
            'Uses HTTP methods as function (get, post, patch, put, delete)',
            'It is similar to a traditional Django view',
            'Gives you the most control over your logic',
            'Is mapped manually to URLs'
        ]

        return Response({'message': 'Hello!', 'an_apiview': an_apiview})

    # metoda za POST response
    def post(self, request):
        """Create a hello message with our name."""

        serializer = serializers.UpravljanjeSerializer(data=request.data)

        # provjeri da serializer ima ispravni data
        if serializer.is_valid():
            name = serializer.data.get('name')
            message = 'Hello {0}'.format(name)
            return Response({'message': message})

        else:
            return Response(
                serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    # Http response
    def put (self, request, pk=None):
        """Handles updating object."""

        return Response({'method': 'put'})

    # Partialy update object
    def patch(self, request, pk=None):
        """Patch request, only updates fields provided in the request."""

        return Response({'method': 'patch'})

    def delete(self, request, pk=None):
        """Delete an object."""

        return Response({'method':'delete'})

# API metoda linije pogona
# Podržava: POST, GET, PUT, PATCH, DELETE
class UpravljanjeViewSet(viewsets.ModelViewSet):
    queryset = Upravljanje.objects.all()
    serializer_class = UpravljanjeSerializer
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        content = {
            'status': 'request was permitted'
        }
        return Response(content)

# API metoda linije pogona za preuzimanje statusa
# Podržava: GET
class CvorViewSet(generics.ListAPIView):
    serializer_class = CvorSerializer
    permission_classes = (AllowAny,)
    def get_queryset(self):
        queryset = Upravljanje.objects.all()
        kod_id = self.request.query_params.get('kod', None)
        # Ukoliko postoji aplikacija za pogon2, postaviti kod='pogon2'
        # Ukoliko postoji aplikacija za pogon3, postaviti kod='pogon3'
        queryset = queryset.filter(kod='pogon1')
        return queryset

pogon1/views.py
# Function-Based-Views

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from .forms import UpravljanjeForm
from .models import Upravljanje, camera
from .upravljanje import *

# Kreiranje novog objekta u pogonu
def upravljanje_create(request):
    """Pogled za kreiranje novog objekta."""

    # POST metoda
    if not request.user.is_staff or not request.user.is_superuser:
        messages.error(request, 'Dozvoljeno sa privilegiranim racunom')

    if not request.user.is_authenticated():
        messages.error(request, 'Potrebno se prijaviti')

    else:
        form = UpravljanjeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            # message success
            messages.success(request, 'Uspjesno kreirano')
            return HttpResponseRedirect(instance.get_absolute_url())

        context = {
            'form':form,
        }
        return render(request, 'pogon1/upravljanje_form.html', context)

    # Ako korisnik nije prijavljen, ne vraća sadržaj pogleda
    return render(request, 'pogon1/upravljanje_form.html')

def upravljanje_detail(request, id=None):
    """Pogled za prikaz detalja kreiranog objekta"""

    instance = get_object_or_404(Upravljanje, id=id)
    context = {
        'title':instance.title,
        'instance':instance,
    }
    return render(request, 'pogon1/upravljanje_detail.html', context)

def upravljanje_list(request):
    """Pogled za prikaz svih kreiranih objekata."""

    if not request.user.is_staff or not request.user.is_superuser:
        messages.error(request, 'Dozvoljeno sa privilegiranim racunom')

    if not request.user.is_authenticated():
        messages.error(request, 'Potrebno se prijaviti')

    else:
        queryset = Upravljanje.objects.filter(korisnik=request.user)

        # Implementirano pretraživanje objekata prema ključnim riječima:
        #     - prema naslovu objekta ili korisnika koji je kreirao objekt
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
    				Q(title__icontains=query)|
    				Q(content__icontains=query)|
    				Q(korisnik__first_name__icontains=query) |
    				Q(korisnik__last_name__icontains=query)
    				).distinct()
        if request.user.is_authenticated:
            context = {
                'title':'Lista objekata',
                'object_list':queryset,
            }
        else:
            context = {
                'title':'List'
            }
        return render(request, 'pogon1/upravljanje_list.html', context)

    # Ako korisnik nije prijavljen, ne vraća sadržaj pogleda
    return render(request, 'pogon1/upravljanje_list.html')

def upravljanje_update(request, id=None): # retrieve
    """Pogled za izmjenu detalja postojećeg objekta."""

    if not request.user.is_staff or not request.user.is_superuser:
        # Ako korisnik nije prijavljen, vraća stranica nije pronađena
        raise Http404
    instance = get_object_or_404(Upravljanje, id=id)
    form = UpravljanjeForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        # Statusna poruka
        messages.success(request, 'Uspjesno spremljeno')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title':instance.title,
        'instance':instance,
        'form':form,
    }
    return render(request, 'pogon1/upravljanje_form.html', context)


def upravljanje_delete(request,id=None): # delete
    """Pogled za brisanje kreiranog objekta."""

    if not request.user.is_staff or not request.user.is_superuser:
        # Ako korisnik nije prijavljen, vraća stranica nije pronađena
        raise Http404
    instance = get_object_or_404(Upravljanje, id=id)
    instance.delete()
    messages.success(request, 'Uspjesno obrisano')
    # Kada je objekt obrisan, potrebno se vratiti trajnom pogledu
    # Vraćaj pogledu za Prikaz svih kreiranih objekata
    return redirect('pogon1:list')

def pogon(request):
    """Pogled za upravljanje lijom pogona."""

    # Preusmjeri pogled ukoliko korisnik nije prijavljen
    if not request.user.is_authenticated():
        messages.error(request, 'Potrebno se prijaviti')
        return render(request, 'pogon1/dokumentacija.html')

    # Prikaži pogled ukoliko je korisnik prijavljen
    else:
        # Odabir objekta kojim se upravlja
        #    - objekti pogona: lanci, sušara, itd.
        korisnika_aktivno = User.objects.count()
        queryset = Upravljanje.objects.filter(korisnik=request.user)
        if request.method == 'POST':
            model = request.POST.get('dropdown1')
            # Ukoliko postoji aplikacija za pogon2, postaviti kod='pogon2'
            # Ukoliko postoji aplikacija za pogon3, postaviti kod='pogon3'
            Upravljanje.objects.filter(kod='pogon1').update(model=model)
            print(model)
            messages.success(request, 'Odabrano: ' + model)
        else:
            # GET metoda
            # Izvrši naredbe pogona koje traži operater
            if 'cmd' in request.GET and request.GET['cmd']:
                cmd = request.GET['cmd']

                # Kamera
                if cmd == 'record':
                    camera.record()

                # Kamera
                if cmd == 'stop-record':
                    camera.stop()

                # Kamera
                if cmd == 'take-photo':
                    camera.photo()

                # RPi3 GPIO upravljanje: Promjena smjera, pauziraj, zaustavi
                motor_control(cmd)

                # RPi3 GPIO pin upravljanje: Promjena brzine
                if (cmd == 'brze') or (cmd =='sporije'):
                    speed_control(cmd)

                # Obavijesti API priključak
                # Za API usluge s kojima radi linija: Telegram
                # Ostaviti ovako za Twitter ili Facebook - ako treba više usluga
                Upravljanje.objects.filter(kod='pogon1').update(extra=cmd)

        context = {
            'korisnika_aktivno': korisnika_aktivno,
            'object_list':queryset,
        }

        return render(request, 'pogon1/pogon.html', context)

def dokumentacija(request):
    """
        Pogled za prikaz dokumentacije pogona.
        Pogled koji se vraća ukoliko korisnik nije prijavljen.
    """

    if not request.user.is_authenticated():
        messages.error(request, 'Potrebno se prijaviti')
    return render(request, 'pogon1/dokumentacija.html')


def upravljanje_prijava(request):
    """Pogled za prijavu korisnika u pogon."""

    # POST metoda
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                obj = Upravljanje.objects.filter(korisnik=request.user)
                # Statusna poruka
                messages.success(request, 'Uspjesno prijavljen')
                return render(request, 'pogon1/upravljanje_prijava.html', {'ispitivanje': obj})
            else:
                # Statusna poruka
                messages.error(request, 'Tvoj račun je blokiran od strane administratora')
                return render(request, 'pogon1/upravljanje_prijava.html')
        else:
            messages.error(request, 'Neispravni korisnički podaci')
            return render(request, 'pogon1/upravljanje_prijava.html')

    # Ako korisnik nije prijavljen, ne vraća sadržaj pogleda
    return render(request, 'pogon1/upravljanje_prijava.html')

def upravljanje_odjava(request):
    form = UpravljanjeForm(request.POST or None)
    logout(request)
    # Statusna poruka
    messages.success(request, 'Uspjesno odjavljen')
    context = {
        'form': form,
    }
    return render(request, 'pogon1/dokumentacija.html', context)

templates/pogon1/about.html
{% extends 'pogon1/min/base.html' %}

{% load staticfiles svg %}

{% block title %}O aplikaciji{% endblock %}

{% block sadrzaj %}
<div class="content-fix-padding">
  <div class="container-fluid">
    <div class="row">
      <p>O aplikaciji linije pogona</p>
    </div>
</div>
{% endblock sadrzaj %}

templates/pogon1/pogon.html
{% extends 'pogon1/min/base.html' %}

{% load staticfiles svg %}

{% block title %}{{ user.username }} Linija pogona{% endblock title %}

{% block sadrzaj %}

<div class="content-fix-padding">
  <!-- Page content 1 -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <div class="panel panel-success">
          <div class="panel-heading">
              Korisnik
          </div>
          <div class="panel-body">
            <h4>Ime: {{ user }}</h4>
            <h4>Korisnika: {{ korisnika_aktivno }}</h4>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="panel panel-success">
          <div class="panel-heading">
              Signali
          </div>
          <div class="panel-body">
            <div class="col-md-2 col-xs-2 col-sm-2 placeholder text-center">
              <div id="signali-lijevo" class="img-responsive">{% svg 'SUN' %}</div>
              <h4>Lijevo</h4>
            </div>
            <div class="col-md-2 col-xs-2 col-sm-2 placeholder text-center">
              <div id="signali-desno" class="img-responsive">{% svg 'SUN' %}</div>
              <h4>Desno</h4>
            </div>
            <div class="col-md-2 col-xs-2 col-sm-2 placeholder text-center">
              <div id="signali-brze" class="img-responsive">{% svg 'SUN' %}</div>
              <h4>Brže</h4>
            </div>
            <div class="col-md-2 col-xs-2 col-sm-2 placeholder text-center">
              <div id="signali-sporije" class="img-responsive">{% svg 'SUN' %}</div>
              <h4>Sporije</h4>
            </div>
            <div class="col-md-2 col-xs-2 col-sm-2 placeholder text-center">
              <div id="signali-pauza" class="img-responsive">{% svg 'SUN' %}</div>
              <h4>Pauza</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /#page-content-wrapper -->

  <!-- Page content 2 -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="panel panel-danger">
          <div class="panel-heading">

            <form action="{% url 'pogon1:pogon' %}" method="POST">{% csrf_token %}
            <table>
              <tr><td style="padding-right:4px;">Upravljanje modelima: </td>
                <td style="padding-right:10px;">
                  <select name="dropdown1">
                    {% if object_list %}
                      {% for object in object_list %}
                      <option  value="{{ object.kod }}">{{ object.kod }}</option>
                      {% endfor %}
                    {% endif %}
                  </select>
                </td>
                <td><input class="btn btn-default" type="submit" value="Upravljaj" /></td>
              </tr>
            </table>


          </div>
          <div class="panel-body">
            <div class="container-fluid">
              <div class="col-md-3 col-xs-3 col-sm-3 kamera"></div>
               <a class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv" style="transform: rotate(270deg);"><object onclick="fwd();">{% svg 'ARROW' %}</object></a>
              <div class="col-md-3 col-xs-3 col-sm-3 kamera"></div>
              <a class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv"><object onclick="stop_linija();">{% svg 'POWER' %}</object></a>
            </div>

            <div class="container-fluid">
              <a class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv" style="transform: rotate(180deg);"><object onclick="lijevo();">{% svg 'ARROW' %}</object></a>
              <a class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv stop"><object onclick="pauziraj();">{% svg 'PAUSE' %}</object></a>
              <a class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv" style="transform: rotate(0deg);"><object onclick="desno();">{% svg 'ARROW' %}</object></a>
              <!-- s -->
              <!-- image trigger modal -->
              <a data-target="#myModal" data-toggle="modal" role="button" class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv">{% svg 'SETTINGS' %}</a>
              <!-- Modal HTML -->
               <div id="myModal" class="modal fade">
                   <div class="modal-dialog">
                       <div class="modal-content">
                           <div class="modal-header">
                               <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                               <h4 class="modal-title">Odabir modela za upravljanje</h4>
                           </div>
                           <div class="modal-body">


                             <form>
                              <div class="form-group">
                                <label for="sel1">Select list (select one):</label>
                                <select class="form-control" id="sel1">
                                  {% if object_list %}
                                    {% for object in object_list %}
                                    <option>{{ object.title }}</option>
                                    {% endfor %}
                                  {% endif %}
                                </select>
                                <br>
                                <label for="sel2">Mutiple select list (hold shift to select more than one):</label>
                                <select multiple class="form-control" id="sel2">
                                  {% if object_list %}
                                    {% for object in object_list %}
                                    <option>{{ object.title }}</option>
                                    {% endfor %}
                                  {% endif %}
                                </select>
                              </div>
                            </form>


                           </div>
                           <div class="modal-footer">
                               <button type="button" class="btn btn-primary" data-dismiss="modal">Zatvori</button>
                           </div>
                       </div>
                   </div>
               </div>

             <!-- s -->
            </div>

            <div class="container-fluid">
              <div class="col-md-3 col-xs-3 col-sm-3 kamera"></div>
              <a class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv" style="transform: rotate(90deg);"><object onclick="bwd();">{% svg 'ARROW' %}</object></a>
              <div class="col-md-3 col-xs-3 col-sm-3 kamera"></div>
              <a class="col-md-3 col-xs-3 col-sm-3 kamera btn btn-default btn-mv"><object onclick="send_mail();">{% svg 'MAIL' %}</object></a>
            </div>

          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="panel panel-success">
          <div class="panel-heading">
              Kamera
          </div>
          <div class="panel-body">
            <a class="col-md-9 col-xs-3 col-sm-3 kamera start btn btn-default btn-mv"><object onclick="record();">{% svg 'PLAY' %}</object></a>
            <a class="col-md-9 col-xs-3 col-sm-3 kamera start btn btn-default btn-mv stop"><object onclick="stop_record();">{% svg 'STOP' %}</object></a>
            <a class="col-md-9 col-xs-3 col-sm-3 kamera uslikaj btn btn-default btn-mv"><object onclick="take_photo();">{% svg 'CAMERA' %}</object></a>
          </div>
        </div>
      </div>
    </div>
  </div><!-- /#page-content-wrapper -->

</div><!-- /#content-fix-padding -->

<script src="{% static 'js/custom.js' %}"></script>

{% endblock sadrzaj %}

templates/pogon1/upravljanje_detail.html
{% extends 'pogon1/min/base.html' %}


{% block sadrzaj %}


  {% if instance.image %}
  <img src='{{ instance.image.url }}' class='img-responsive' />
  {% endif %}

<h1>{{ title }} <small>{{ instance.timestamp }}</small></h1>

{{ instance.content|linebreaks }}<br/>

{% endblock sadrzaj %}

templates/pogon1/upravljanje_form.html
{% extends 'pogon1/min/base.html' %}

{% block sadrzaj %}

<h1>Form | <a href="{% url 'pogon1:list' %}">List</a></h1>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form.as_p }}
<input type='submit' class='btn btn-default' value='Novi objekt' />
</form>


{% endblock sadrzaj %}

templates/pogon1/upravljanje_list.html
{% extends 'pogon1/min/base.html' %}

{% block sadrzaj %}

<h1><a href="{% url 'pogon1:list' %}">{{ title }}</a> |
<a href="{% url 'pogon1:create' %}">Izradi objekt</a>
</h1>

<div class="container" style="padding:20px;">
  <form method='GET' action=''>
    <input type='text' name='q' placeholder='Pretrazi upravljanje' />
    <input type='submit' value='Trazi' />
  </form>
</div>

<div class="row">

  {% if object_list %}
  <div class="table">
      <table class="table table-hover">
          <thead class="table-default">
              <tr>
                  <th>Naziv</th>
                  <th>Kreirao</th>
                  <th>Obnovljen</th>
                  <th>Kod</th>
                  <th>Model</th>
                  <th>Extra</th>
                  <th>Slika</th>
              </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
            <tr>
                <td><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></td>
                <td>{{ object.korisnik }}</td>
                <td>{{ object.updated }}</td>
                <td><small>{{ object.kod }}</small></td>
                <td><small>{{ object.model }}</small></td>
                <td><small>{{ object.extra }}</small></td>
                {% if object.image %}
                <td><a href="{{ object.image.url }}">{{ object.image.name }}</a></td>
                {% else %}
                <td></td>
                {% endif %}
            </tr>
            {% endfor %}
          </tbody>
      </table>
  </div>
  {% endif %}


</div>


{% endblock sadrzaj %}

templates/pogon1/upravljanje_prijava.html
{% extends 'pogon1/min/base.html' %}

{% block title %}Prijava sa korisnickim podacima{% endblock %}

{% block sadrzaj %}

<div class="content-fix-padding">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-body">
            <h3>Log In</h3>
            <form class="form-horizontal" role="form" action="{% url 'pogon1:prijava'%}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                <label class="control-label col-sm-4" for="id_username">
                    Username:
                </label>
                <div class="col-sm-6">
                  <input id="id_username" maxlength="30" name="username" type="text">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-4" for="id_password">
                    Password:
                </label>
                <div class="col-sm-6">
                    <input id="id_password" maxlength="30" name="password" type="password">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div><!-- /#content-fix-padding -->
{% endblock sadrzaj %}